@extends('layouts.admin')

@section('title', 'Katalog')

@section('content')
<div class="flex flex-wrap items-end justify-between gap-4"><div><h1 class="text-2xl font-semibold">Katalog</h1><p class="mt-1 text-sm text-sea">{{ $catalogs->total() }} entri</p></div><a href="{{ route('superadmin.catalogs.create') }}" class="inline-flex min-h-11 items-center rounded-md bg-sea px-4 font-semibold text-white">Tambah katalog</a></div>
<form method="GET" class="mt-5 grid gap-3 md:grid-cols-[1fr_200px_180px_auto]"><label class="sr-only" for="search">Cari katalog</label><input id="search" name="search" value="{{ request('search') }}" placeholder="Nama atau alamat" class="min-h-11 rounded-md border border-sky px-3"><select name="type" aria-label="Kategori" class="min-h-11 rounded-md border border-sky px-3"><option value="">Semua kategori</option>@foreach ($typeLabels as $key => $label)<option value="{{ $key }}" @selected(request('type') === $key)>{{ $label }}</option>@endforeach</select><select name="status" aria-label="Status" class="min-h-11 rounded-md border border-sky px-3"><option value="">Semua status</option><option value="published" @selected(request('status') === 'published')>Published</option><option value="draft" @selected(request('status') === 'draft')>Draf</option></select><button class="min-h-11 rounded-md border border-sea px-4 font-semibold text-sea">Filter</button></form>
<div class="mt-5 overflow-x-auto rounded-md border border-sky bg-white"><table class="w-full min-w-[850px] text-left text-sm"><thead class="bg-sky"><tr><th class="p-3">Katalog</th><th class="p-3">Kategori</th><th class="p-3">Status</th><th class="p-3">Catalog Admin</th><th class="p-3">Aksi</th></tr></thead><tbody>@forelse ($catalogs as $catalog)<tr class="border-t border-sky align-top"><td class="p-3"><a class="font-semibold text-sea" href="{{ route('superadmin.catalogs.show', $catalog) }}">{{ $catalog->name }}</a><p class="mt-1 text-xs text-sea">{{ $catalog->address }}</p></td><td class="p-3">{{ $catalog->type_label }}<br><span class="text-xs text-sea">{{ $catalog->sub_type }}</span></td><td class="p-3">{{ $catalog->status === 'published' ? 'Published' : 'Draf' }}</td><td class="p-3">{{ $catalog->admin?->name ?? 'Belum ada' }}</td><td class="p-3"><div class="flex flex-wrap gap-2"><a class="text-sea underline" href="{{ route('superadmin.catalogs.edit', $catalog) }}">Edit</a><a class="text-sea underline" href="{{ route('superadmin.catalogs.qr', $catalog) }}">QR</a>@if ($catalog->status === 'published')<form method="POST" action="{{ route('superadmin.catalogs.unpublish', $catalog) }}">@csrf<button class="text-amber-800 underline">Jadikan draf</button></form>@else<form method="POST" action="{{ route('superadmin.catalogs.publish', $catalog) }}">@csrf<button class="text-green-800 underline">Publish</button></form>@endif</div></td></tr>@empty<tr><td colspan="5" class="p-6 text-center text-sea">Belum ada katalog yang cocok.</td></tr>@endforelse</tbody></table></div>
<div class="mt-5">{{ $catalogs->links() }}</div>
@endsection
