@extends('layouts.admin')

@section('title', $catalog->name)

@section('content')
<div class="flex flex-wrap items-start justify-between gap-4"><div><a href="{{ route('superadmin.catalogs.index') }}" class="text-sm text-sea">&larr; Daftar katalog</a><h1 class="mt-2 text-2xl font-semibold">{{ $catalog->name }}</h1><p class="mt-1 text-sea">{{ $catalog->type_label }} · {{ $catalog->sub_type }} · {{ $catalog->status === 'published' ? 'Published' : 'Draf' }}</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('superadmin.catalogs.edit', $catalog) }}" class="inline-flex min-h-11 items-center rounded-md border border-sea px-4 text-sea">Edit</a><a href="{{ route('superadmin.catalogs.qr', $catalog) }}" class="inline-flex min-h-11 items-center rounded-md bg-sea px-4 text-white">QR Code</a><a href="{{ route('superadmin.catalogs.activities.index', $catalog) }}" class="inline-flex min-h-11 items-center rounded-md border border-sea px-4 text-sea">Berita & Kegiatan</a>@if ($catalog->type === 'umkm')<a href="{{ route('superadmin.catalogs.products.index', $catalog) }}" class="inline-flex min-h-11 items-center rounded-md border border-sea px-4 text-sea">Produk</a>@endif</div></div>
<div class="mt-6 grid gap-6 lg:grid-cols-[240px_1fr]"><img src="{{ $catalog->photo_url }}" alt="Foto {{ $catalog->name }}" class="aspect-[4/3] w-full rounded-md object-cover"><dl class="grid gap-4 bg-white p-5 sm:grid-cols-2"><div><dt class="text-sm text-sea">Alamat</dt><dd class="mt-1">{{ $catalog->address }}</dd></div><div><dt class="text-sm text-sea">{{ $catalog->contact_person_label }}</dt><dd class="mt-1">{{ $catalog->contact_person ?: 'Belum diisi' }}</dd></div><div><dt class="text-sm text-sea">Koordinat</dt><dd class="mt-1 font-mono">{{ $catalog->latitude ?? '—' }}, {{ $catalog->longitude ?? '—' }}</dd></div><div><dt class="text-sm text-sea">Email / Telepon</dt><dd class="mt-1">{{ $catalog->email ?: '—' }} · {{ $catalog->phone ?: '—' }}</dd></div><div class="sm:col-span-2"><dt class="text-sm text-sea">Deskripsi</dt><dd class="mt-1 whitespace-pre-line">{{ $catalog->description ?: 'Belum ada deskripsi.' }}</dd></div><div><dt class="text-sm text-sea">Slug stabil</dt><dd class="mt-1">{{ $catalog->slug }}</dd></div><div><dt class="text-sm text-sea">Catalog Admin</dt><dd class="mt-1">{{ $catalog->admin?->name ?? 'Belum ditetapkan' }}</dd></div></dl></div>
@if ($catalog->type === 'umkm')<section class="mt-8"><h2 class="text-xl font-semibold">Produk ({{ $catalog->products->count() }})</h2><ul class="mt-3 divide-y divide-sky bg-white px-4">@forelse ($catalog->products as $product)<li class="flex justify-between gap-4 py-3"><span>{{ $product->name }}</span><span class="text-sm text-sea">{{ $product->formatted_price }} · {{ $product->availability_label }}</span></li>@empty<li class="py-4 text-sea">Belum ada produk.</li>@endforelse</ul></section>@endif
<div class="mt-8 border-t border-sky pt-5"><form method="POST" action="{{ route('superadmin.catalogs.destroy', $catalog) }}" onsubmit="return confirm('Hapus katalog ini beserta produk dan akun admin terkait?')">@csrf @method('DELETE')<button class="min-h-11 rounded-md border border-red-700 px-4 text-red-800">Hapus katalog</button></form></div>
@endsection
