@extends('layouts.admin')

@section('title', 'Catalog Admin')

@section('content')
<div class="flex flex-wrap items-end justify-between gap-4"><div><h1 class="text-2xl font-semibold">Catalog Admin</h1><p class="mt-1 text-sm text-sea">{{ $admins->total() }} akun</p></div><a href="{{ route('superadmin.admins.create') }}" class="inline-flex min-h-11 items-center rounded-md bg-sea px-4 text-white">Buat akun admin</a></div>
<form method="GET" class="mt-5 flex flex-wrap gap-3"><label class="sr-only" for="search">Cari admin</label><input id="search" name="search" value="{{ request('search') }}" placeholder="Nama atau email" class="min-h-11 min-w-56 rounded-md border border-sky px-3"><select name="status" aria-label="Status akun" class="min-h-11 rounded-md border border-sky px-3"><option value="">Semua akun</option><option value="active" @selected(request('status') === 'active')>Aktif</option><option value="inactive" @selected(request('status') === 'inactive')>Nonaktif</option></select><button class="min-h-11 rounded-md border border-sea px-4 text-sea">Filter</button></form>
<div class="mt-5 overflow-x-auto rounded-md border border-sky bg-white"><table class="w-full min-w-[680px] text-left text-sm"><thead class="bg-sky"><tr><th class="p-3">Admin</th><th class="p-3">Katalog</th><th class="p-3">Status</th><th class="p-3">Aksi</th></tr></thead><tbody>@forelse ($admins as $admin)<tr class="border-t border-sky"><td class="p-3">{{ $admin->name }}<p class="text-xs text-sea">{{ $admin->email }}</p></td><td class="p-3">{{ $admin->catalog?->name ?? 'Katalog tidak tersedia' }}</td><td class="p-3">{{ $admin->is_active ? 'Aktif' : 'Nonaktif' }}</td><td class="p-3"><div class="flex gap-3"><a href="{{ route('superadmin.admins.edit', $admin) }}" class="text-sea underline">Edit</a><form method="POST" action="{{ route('superadmin.admins.toggle-active', $admin) }}">@csrf<button class="text-sea underline">{{ $admin->is_active ? 'Nonaktifkan' : 'Aktifkan' }}</button></form><form method="POST" action="{{ route('superadmin.admins.destroy', $admin) }}" onsubmit="return confirm('Hapus akun admin ini?')">@csrf @method('DELETE')<button class="text-red-800 underline">Hapus</button></form></div></td></tr>@empty<tr><td colspan="4" class="p-6 text-center text-sea">Belum ada Catalog Admin.</td></tr>@endforelse</tbody></table></div><div class="mt-5">{{ $admins->links() }}</div>
@endsection
